################################################################################
##
##  Purpose: Provide a api for Beer data
##  Email: phriscage@gmail.com
##
################################################################################
version: "3.4"
services:
  details-api:
    build:
      context: details
      dockerfile: Dockerfile
    image: phriscage/beer-details-api:${TAG}
  #orders:
    #build:
      #context: orders
      #dockerfile: orders/Dockerfile
    #image: phriscage/beer-orders:${TAG}
