################################################################################
##
##  Purpose: Provide a api for Beer data
##  Email: phriscage@gmail.com
##
################################################################################
version: "3.4"
services:
  details-api:
    image: phriscage/beer-details-api:${TAG}
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:${PWD}
    #working_dir: ${PWD}
    entrypoint: 
      - python 
      - ${PWD}/details/api/main.py
  #orders:
    #build:
      #context: orders
      #dockerfile: orders/Dockerfile
    #image: phriscage/beer-orders:${TAG}
