################################################################################
##
##  Purpose: Provide a api for Beer data
##  Email: phriscage@gmail.com
##
################################################################################
version: "3.4"
services:
  details-api:
    build:
      context: details
      #dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    image: phriscage/beer-details-api:${TAG}
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:${PWD}
    #working_dir: ${PWD}
    entrypoint: 
      - python 
      - ${PWD}/details/api/main.py
